baseurl         = "https://priceless-wiles-535968.netlify.com/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Andrew Zieffler"
  subtitle    = "biography, CV, portfolio"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = "zief0002"
  githubName = "zief0002"
  linkedinName = ""
  mediumName = ""

  logo = "img/zieffler-logo.png"
  orgName = "AZ"
  orgWebsite = ""
  orgDescription = ""

  showSupport = true

  author = "AZ"
  authorAvatar = "img/andy.png"
  authorLocation = "Minneapolis, MN"
  authorWebsite = "https://zief0002.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95
  